### ISSUE TITLE
System.NullReferenceException: 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by KenionX** [DarthAffe/ScreenCapture.NET#2]
Using the example code, crashing on 
| StackTrace | "   at SharpGen.Runtime.CppObject.get_Item(Int32 index)\r\n   at Vortice.Direct3D11.ID3D11Device.CreateTexture2D(Texture2DDescription descRef, SubresourceData[] initialDataRef)\r\n   at ScreenCapture.NET.DX11ScreenCapture.InitializeCaptureZone(CaptureZone& captureZone)\r\n   at ScreenCapture.NET.DX11ScreenCapture.RegisterCaptureZone(Int32 x, Int32 y, Int32 width, Int32 height, Int32 downscaleLevel)\r\n 

`
            DPIAwareness.Initalize();

            IScreenCaptureService screenCaptureService = new DX11ScreenCaptureService();

            // Get all available graphics cards
            IEnumerable<GraphicsCard> graphicsCards = screenCaptureService.GetGraphicsCards();

            // Get the displays from the graphics card(s) you are interested in
            IEnumerable<Display> displays = screenCaptureService.GetDisplays(graphicsCards.First());

            // Create a screen-capture for all screens you want to capture
            IScreenCapture screenCapture = screenCaptureService.GetScreenCapture(displays.First());

            // Register the regions you want to capture om the screen
            // Capture the whole screen
            CaptureZone fullscreen = screenCapture.RegisterCaptureZone(0, 0, screenCapture.Display.Width, screenCapture.Display.Height);`

**Comment by KenionX** [comment]
Seams like this issue only appears if the code is running on a WPF Ui Thread

**Comment by DarthAffe** [comment]
Hey, I can reproduce this exception on a WPF UI Thread, but so far I've no idea why it is thrown - I'm investigating.

**Comment by DarthAffe** [comment]
Hey, I still have no idea what causes this error in that specific case but it's fixed/workarounded with version 1.1 (https://github.com/DarthAffe/ScreenCapture.NET/commit/aa1069310e180d8fa8cb41795ba605b79f7db416)
