### ISSUE TITLE
Bug ScreenCapture.NET.DX11

### ISSUE THREAD

**Issue by tjma2001** [DarthAffe/ScreenCapture.NET#20]
When I try and instantiate a screencapture service 

```IScreenCaptureService screenCaptureService = new DX11ScreenCaptureService();```

I get the following error. 

```Method 'get_ColorFormat' in type 'ScreenCapture.NET.IColor' from assembly 'ScreenCapture.NET, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null' cannot be a static and a virtual.```

Using .Net 6.0. The issue occurs on both ScreenCapture.NET v2.0.0 and v2.0.1

**Comment by DarthAffe** [comment]
Just to let you know: I was able to reproduce, but currently I'm completely lost why that's happening - still investigating.
