### ISSUE TITLE
Featurerequest IImage.Convert();

### ISSUE THREAD

**Issue by sheepchen** [DarthAffe/ScreenCapture.NET#22]
It would be nice if IImage was convertable either to Image or to Bitmap.

Like:

ICaptureZone zone = screen.RegisterCaptureZone(1080, 896, 57, 35, downscaleLevel: 1);
screen.CaptureScreen();
using (zone.Lock())
{ 
  IImage img = GEAR.Image;
  Bitmap bmp = img.convert();
}

**Comment by DarthAffe** [comment]
This is out of scope as it would require a reference to System.Drawing. Also for IImage it's quite hard to implement a general solution as you don't know about the layout of the data.

You can use an extension like this, but this only works for providers using BGRA-colors (all of the currently implemented capture-providers are doing this).

```csharp
public static class ImageExtension
{
    public static Bitmap ToBitmap(this IImage image) => image.AsRefImage<ColorBGRA>().ToBitmap();
    public static Bitmap ToBitmap(this Image<ColorBGRA> image) => image.AsRefImage<ColorBGRA>().ToBitmap();

    public static unsafe Bitmap ToBitmap(this RefImage<ColorBGRA> image)
    {
        Bitmap output = new(image.Width, image.Height, PixelFormat.Format32bppArgb);
        System.Drawing.Rectangle rect = new(0, 0, image.Width, image.Height);
        BitmapData bmpData = output.LockBits(rect, ImageLockMode.ReadWrite, output.PixelFormat);

        nint ptr = bmpData.Scan0;
        foreach (ReadOnlyRefEnumerable<ColorBGRA> row in image.Rows)
        {
            row.CopyTo(new Span<ColorBGRA>((void*)ptr, bmpData.Stride));
            ptr += bmpData.Stride;
        }

        output.UnlockBits(bmpData);
        return output;
    }
}
```

**Comment by sheepchen** [comment]
Dear DarthAffe,

thats understandable.

Big thanks for the code you provided. It works and is completly fine for my application.
