### ISSUE TITLE
Convert IImage 

### ISSUE THREAD

**Issue by krysek89** [DarthAffe/ScreenCapture.NET#28]
Hello, how can i convert IImage or other object to Bitmap ? 
![image](https://github.com/DarthAffe/ScreenCapture.NET/assets/61799427/ff283c25-0f33-42dc-8c6f-2c8adc9f5634)

![image](https://github.com/DarthAffe/ScreenCapture.NET/assets/61799427/665e0508-a682-4836-bf67-6c95c1eb3ea4)

not working...

**Comment by krysek89** [comment]
I changed to DX9ScreenCaptureService and starting works.

**Comment by DarthAffe** [comment]
You can't just copy the whole buffer due to the possible difference in the stride between the bitmap and the data itself.
Here is an example that prevents this by copying line by line:
https://github.com/DarthAffe/ScreenCapture.NET/issues/22#issuecomment-1763063003
