### ISSUE TITLE
When using the IColor interface in IImage, will it cause a lot of boxing problems?

### ISSUE THREAD

**Issue by sgf** [DarthAffe/ScreenCapture.NET#35]
Perhaps making IImage a generic parameter interface is an option. 
Of course, this may bring new problems, such as generic parameter pollution.

**Comment by DarthAffe** [comment]
Making the interface generic would contradict the reason for it to be there (cases where you don't know the color-format). If you do know it, it's always better to get the RefImage and work with that to avoid boxing.

**Comment by sgf** [comment]
The pixel formats you support must be known. Otherwise you can't handle them.
Even if they are unknown, the image pixel implementor must implement the pixel processing themselves.
