### ISSUE TITLE
does it could be support direct get image spec format(like Mono8bit) ?

### ISSUE THREAD

**Issue by sgf** [DarthAffe/ScreenCapture.NET#38]
Is it possible to support obtaining images directly in a specified format (such as grayscale Mono8bit)?

**Comment by DarthAffe** [comment]
That depends a bit on what you want to achieve, but the answer is most likely 'no, you have to convert after capturing'.

The data is always returned in 32-bit BGRA-format by the API an simply copied and returned. In theory it's possible change that to always represent the color format of the actual front-buffer (which most likely is BGRA anyway), but that would only give you any benefit if you have a application using exclusive fullscreen with an 8 bit color format.

**Comment by sgf** [comment]
thanks
